### ISSUE TITLE
Discrepencies for nep5 balance between C# and go version

### ISSUE THREAD

**Issue by adrienmo** [nspcc-dev/neo-go#1511]
```
curl  -X POST -d '{"jsonrpc": "2.0", "method": "getnep5balances", "params": ["AHhAf8S1DAx8DgSePSnTH3Mp2nn27FtBn7"], "id": 1}'      https://rpc4.go.nspcc.ru:10331
{"id":1,"jsonrpc":"2.0","result":{"balance":[{"asset_hash":"3a4acd3647086e7c44398aac0349802e6a171129","amount":"1310267000000","last_updated_block":6163832}],"address":"AHhAf8S1DAx8DgSePSnTH3Mp2nn27FtBn7"}}

curl  -X POST -d '{"jsonrpc": "2.0", "method": "getnep5balances", "params": ["AHhAf8S1DAx8DgSePSnTH3Mp2nn27FtBn7"], "id": 1}' http://seed2.ngd.network:10332   
{"jsonrpc":"2.0","id":1,"result":{"balance":[{"asset_hash":"3a4acd3647086e7c44398aac0349802e6a171129","amount":"3053340064053","last_updated_block":6345073}],"address":"AHhAf8S1DAx8DgSePSnTH3Mp2nn27FtBn7"}}
```

GO version reports 13000 NEX, C# version reports 30000 NEX.

**Comment by hal0x2328** [comment]
That node just has incorrect state, probably due to the Neo 2.12.x changes, meaning it just needs a resync. If you try the same query on the Go node at https://rpc1.go.nspcc.ru:10331 (running the same version, NEO-GO:0.78.0) it returns the same result as the C# node.

**Comment by adrienmo** [comment]
@hal0x2328 all our node are corrupted:
- https://neonode1.nash.io 
- https://neonode2.nash.io 
- https://neonode3.nash.io 
Is there a data dump available from the `https://rpc1.go.nspcc.ru:10331` node so we can have a quick recovery?

**Comment by hal0x2328** [comment]
Maybe @roman-khimov can help with that

**Comment by roman-khimov** [comment]
I have a dump made at 6215139 which is not that far away from the current:
https://drive.google.com/file/d/1HmP5VNbfiTih5tbSrVE0tKpHP3kFqLdG/view?usp=sharing
It's a BoltDB dump (we tend to use that for our nodes), so you need to configure your node appropriately.

And yes, it's quite easy to check stateroot hashes now to see if everything is fine with a node.

**Comment by adrienmo** [comment]
@roman-khimov After restoring it, it seems this dump is corrupted as well. You probably should do a new one :)

**Comment by roman-khimov** [comment]
Did you compare state roots from it? I'm downloading it at the moment for a local check.

**Comment by roman-khimov** [comment]
@adrienmo, I've finally downloaded it, just to make sure we're talking about the same thing, here is the SHA256 hash of it: 91ef70a9345e06ba92e8ff16ae1e3ebf10111527a57d23aac1acbaed589e6edb.

Then I did the following changes to the default configuration:
```
--- a/config/protocol.mainnet.yml
+++ b/config/protocol.mainnet.yml
@@ -15,16 +15,6 @@ ProtocolConfiguration:
   - 02aaec38470f6aad0042c6e877cfd8087d2676b0f516fddd362801b9bd3936399e
   - 02486fd15702c4490a26703112a5cc1d0923fd697a33406bd5a1c00e0013b09a70
   SeedList:
-  - seed1.ngd.network:10333
-  - seed2.ngd.network:10333
-  - seed3.ngd.network:10333
-  - seed4.ngd.network:10333
-  - seed5.ngd.network:10333
-  - seed6.ngd.network:10333
-  - seed7.ngd.network:10333
-  - seed8.ngd.network:10333
-  - seed9.ngd.network:10333
-  - seed10.ngd.network:10333
   SystemFee:
     EnrollmentTransaction: 1000
     IssueTransaction: 500
@@ -43,7 +33,7 @@ ApplicationConfiguration:
   # LogPath could be set up in case you need stdout logs to some proper file.
   # LogPath: "./log/neogo.log"
   DBConfiguration:
-    Type: "leveldb" #other options: 'inmemory','redis','boltdb', 'badgerdb'.
+    Type: "boltdb" #other options: 'inmemory','redis','boltdb', 'badgerdb'.
     # DB type options. Uncomment those you need in case you want to switch DB type.
     LevelDBOptions:
       DataDirectoryPath: "./chains/mainnet"
@@ -51,8 +41,8 @@ ApplicationConfiguration:
   #      Addr: "localhost:6379"
   #      Password: ""
   #      DB: 0
-  #    BoltDBOptions:
-  #      FilePath: "./chains/mainnet.bolt"
+    BoltDBOptions:
+      FilePath: "./chains/mainnet.bolt"
   #    BadgerDBOptions:
   #      BadgerDir: "./chains/mainnet.badger"
   #  Uncomment in order to set up custom address for node.
```
To enable BoltDB and to prevent any kind of network activity, because I've just wanted to see what's inside. Then I ran 0.78.1 build of the node with it (we're not changing anything, so 0.78.0 would be the same):
```
$ ./bin/neo-go -v
neo-go version 0.78.1
$ ./bin/neo-go node -m
2020-10-27T15:06:27.515+0300    INFO    restoring blockchain    {"version": "0.0.9"}

    _   ____________        __________
   / | / / ____/ __ \      / ____/ __ \
  /  |/ / __/ / / / /_____/ / __/ / / /
 / /|  / /___/ /_/ /_____/ /_/ / /_/ /
/_/ |_/_____/\____/      \____/\____/

/NEO-GO:0.78.1/

2020-10-27T15:06:35.362+0300    INFO    service is running      {"service": "Prometheus", "endpoint": ":2112"}
2020-10-27T15:06:35.362+0300    INFO    starting rpc-server     {"endpoint": ":10332"}
2020-10-27T15:06:35.362+0300    INFO    service hasn't started since it's disabled      {"service": "Pprof"}
2020-10-27T15:06:35.362+0300    INFO    node started    {"blockHeight": 6215139, "headerHeight": 6277464}
```

We have block height of 6215139 and state height of 6215131 inside:
```
$ curl -d '{ "jsonrpc": "2.0", "id": 1, "method": "getstateheight", "params": [] }' localhost:10332
{"id":1,"jsonrpc":"2.0","result":{"blockheight":6215139,"stateheight":6215131}}
```
6215131 is verified:
```
$ curl -d '{ "jsonrpc": "2.0", "id": 1, "method": "getstateroot", "params": [6215131] }' localhost:10332 | json_pp 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1510  100  1434  100    76  1400k  76000 --:--:-- --:--:-- --:--:-- 1474k
{
   "id" : 1,
   "result" : {
      "stateroot" : {
         "index" : 6215131,
         "prehash" : "0x2c2dae2a08a4da33d415857ef02a239c115a9208460e94929e008d39c47bb7fb",
         "witness" : {
            "verification" : "5521024c7b7fb6c310fccf1ba33b082519d82964ea93868d676662d4a59ad548df0e7d21025bdf3f181f53e9696227843950deb72dcd374ded17c057159513c3d0abe20b642103b209fd4f53a7170ea4444e0cb0a6bb6a53c2bd016926989cf85f9b0fba17a70c2103b8d9d5771d8f513aa0869b9cc8d50986403b78c6da36890638c3d46a5adce04a2103c346b984b5ad1a7b0ab019f1550fd783108f83a6ca5396b152c7aa302b87ed5b2102ca0e27697b9c248f6f16e085fd0061e26f44da85b58ee835c110caa5ec3ba5542102df48f60e8f3e01c48ff40b9b7f1310d7a8b2a193188befe1c2e3df740e89509357ae",
            "invocation" : "401846df57dc043335651df49b5f208568b11b792a4f86db55880b95a872488fbb8e3bf2b1d826202190c261617c56d6e9f1c33229aea32a5b1ef5c69476c1407140c3e3b517d8a62b17bf69feb6da9dbd5f4439260663905789982a90640956f5151c691240ed93f716ec4f9a37a622024e6d74bc92daf1838c5e8c068f4813af6340114e00bcde0876eacfd356ed1f23acf59c063809b4732d493662549ea990568c79f1256e4f87f3bd20fe91f112685aa16dd27e3e626885883e879bbf0655b4c340081e5299ac05ef55dec77dbab238ff02fb84a0a04b5c0e0a4c32e0090f199c06e0e555bf790b167873bb1108d691bdef4a270d5110941b7ce6c3420b26e85c85405c8c823a865966cf508c2eb03d6d17a0b4e7b4a749da8c6ac53f51b91e6a84ad62ac28805ac3a92a35c1324272fb97bb782ee03d936abfb90bc41b189ea29ece"
         },
         "stateroot" : "0x957758d79749c81da57aca7970c4cf0153d1e4eed6d1012e9635c9af21ede80b",
         "version" : 0
      },
      "flag" : "Verified"
   },
   "jsonrpc" : "2.0"
}
```
Checking with one of seed nodes:
```
$ curl -d '{ "jsonrpc": "2.0", "id": 1, "method": "getstateroot", "params": [6215131] }' seed5.ngd.network:10332 | json_pp 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1509    0  1433  100    76    203     10  0:00:07  0:00:07 --:--:--   305
{
   "result" : {
      "stateroot" : {
         "index" : 6215131,
         "stateroot" : "0x957758d79749c81da57aca7970c4cf0153d1e4eed6d1012e9635c9af21ede80b",
         "prehash" : "0x2c2dae2a08a4da33d415857ef02a239c115a9208460e94929e008d39c47bb7fb",
         "version" : 0,
         "witness" : {
            "invocation" : "401846df57dc043335651df49b5f208568b11b792a4f86db55880b95a872488fbb8e3bf2b1d826202190c261617c56d6e9f1c33229aea32a5b1ef5c69476c1407140c3e3b517d8a62b17bf69feb6da9dbd5f4439260663905789982a90640956f5151c691240ed93f716ec4f9a37a622024e6d74bc92daf1838c5e8c068f4813af6340114e00bcde0876eacfd356ed1f23acf59c063809b4732d493662549ea990568c79f1256e4f87f3bd20fe91f112685aa16dd27e3e626885883e879bbf0655b4c340081e5299ac05ef55dec77dbab238ff02fb84a0a04b5c0e0a4c32e0090f199c06e0e555bf790b167873bb1108d691bdef4a270d5110941b7ce6c3420b26e85c85405c8c823a865966cf508c2eb03d6d17a0b4e7b4a749da8c6ac53f51b91e6a84ad62ac28805ac3a92a35c1324272fb97bb782ee03d936abfb90bc41b189ea29ece",
            "verification" : "5521024c7b7fb6c310fccf1ba33b082519d82964ea93868d676662d4a59ad548df0e7d21025bdf3f181f53e9696227843950deb72dcd374ded17c057159513c3d0abe20b642103b209fd4f53a7170ea4444e0cb0a6bb6a53c2bd016926989cf85f9b0fba17a70c2103b8d9d5771d8f513aa0869b9cc8d50986403b78c6da36890638c3d46a5adce04a2103c346b984b5ad1a7b0ab019f1550fd783108f83a6ca5396b152c7aa302b87ed5b2102ca0e27697b9c248f6f16e085fd0061e26f44da85b58ee835c110caa5ec3ba5542102df48f60e8f3e01c48ff40b9b7f1310d7a8b2a193188befe1c2e3df740e89509357ae"
         }
      },
      "flag" : "Verified"
   },
   "jsonrpc" : "2.0",
   "id" : 1
}
```

Of course the error could've crept in-between 6215131 and 6215139, so we should check 6215139 too. It's not verified in this DB, but it's still there as there a state for this height:
```
$ curl -d '{ "jsonrpc": "2.0", "id": 1, "method": "getstateroot", "params": [6215139] }' localhost:10332 | json_pp 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   334  100   258  100    76   251k  76000 --:--:-- --:--:-- --:--:--  326k
{
   "result" : {
      "flag" : "Unverified",
      "stateroot" : {
         "stateroot" : "0xcc37b4f541bfd20467219afe86478e4574ac2403dc7e1961643daa1fa9d8ee93",
         "version" : 0,
         "prehash" : "0xd6840739f1ada2e355473457eec3e76239bda0e53c33aa71490fa76e4b15a22d",
         "index" : 6215139
      }
   },
   "jsonrpc" : "2.0",
   "id" : 1
}
```
Checking with a seed node:
```
$ curl -d '{ "jsonrpc": "2.0", "id": 1, "method": "getstateroot", "params": [6215139] }' seed5.ngd.network:10332 | json_pp 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1509    0  1433  100    76    545     28  0:00:02  0:00:02 --:--:--   574
{
   "jsonrpc" : "2.0",
   "result" : {
      "stateroot" : {
         "index" : 6215139,
         "stateroot" : "0xcc37b4f541bfd20467219afe86478e4574ac2403dc7e1961643daa1fa9d8ee93",
         "witness" : {
            "invocation" : "4023d1e505c8bd50e8c33119774964110bd3d6a0ef40110b158db1f965df110859a2d3616e18dadf632b2813a2a85ecc62a75f4efd2616a554d673650453c658ff404edafb6742d296bf87ff5cfa0341c01658dbd00fd4c0f08c8b07621e9a6ed47a278a54e3eafd261d886c779702c503588a6c8ffd34f6518ea28b0d8b25c6a63a40403f2ac2a5fcf6d64a110feeacb8e7d8af2a773d53f37e8cbbf65c950b0653c747b889ddc625ada7328f5e2f82a776eafe90c5f443b7ccaab3ef1265c5117f5840885871fbbb96a26a0e22834bbf41b5c14d8e40a7eedfed8a0389078c2e60f76fd9f60007d9704d86e5713bc50bc01588455f59051c20827222a7f33efb73d90b40f31c377c737df4894521ef18feb4fc79ae6f37d00a52a6237a1b5ca75a52800dfcf0b12dcf37f76bd27efbe3d6149ec00470eed4bb8d77547df8f63f8de4a0b8",
            "verification" : "5521024c7b7fb6c310fccf1ba33b082519d82964ea93868d676662d4a59ad548df0e7d21025bdf3f181f53e9696227843950deb72dcd374ded17c057159513c3d0abe20b642103b209fd4f53a7170ea4444e0cb0a6bb6a53c2bd016926989cf85f9b0fba17a70c2103b8d9d5771d8f513aa0869b9cc8d50986403b78c6da36890638c3d46a5adce04a2103c346b984b5ad1a7b0ab019f1550fd783108f83a6ca5396b152c7aa302b87ed5b2102ca0e27697b9c248f6f16e085fd0061e26f44da85b58ee835c110caa5ec3ba5542102df48f60e8f3e01c48ff40b9b7f1310d7a8b2a193188befe1c2e3df740e89509357ae"
         },
         "version" : 0,
         "prehash" : "0xd6840739f1ada2e355473457eec3e76239bda0e53c33aa71490fa76e4b15a22d"
      },
      "flag" : "Verified"
   },
   "id" : 1
}
```
Confirms that it's the same.

So this DB dump is correct and can be used for node bootstrapping.

**Comment by pragyansden** [comment]
I updated the with the new data and checked the configuration… can’t seem to find what’s wrong:

But I am still getting unknown state root error:

```
curl -d '{ "jsonrpc": "2.0", "id": 1, "method": "getstateroot", "params": [6369683] }' localhost:10332 | json_pp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   155  100    79  100    76  79000  76000 --:--:-- --:--:-- --:--:--  151k
{
   "jsonrpc" : "2.0",
   "id" : 1,
   "error" : {
      "code" : -100,
      "message" : "Unknown state root."
   }
}
```
```
It works from seed network…
curl -d '{ "jsonrpc": "2.0", "id": 1, "method": "getstateroot", "params": [6369683] }' seed5.ngd.network:10332 | json_pp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1509    0  1433  100    76  10856    575 --:--:-- --:--:-- --:--:-- 11431
{
   "id" : 1,
   "result" : {
      "flag" : "Verified",
      "stateroot" : {
         "stateroot" : "0x9c9534693815aab331d82cbcf7e8e0bff29f5f5a36d1a9aaa3370b753536fc09",
         "index" : 6369683,
         "prehash" : "0xf9b9992a914f861f4cd346b9b2ddf88046e18a9ea14f72df9e4f444bd08df122",
         "version" : 0,
         "witness" : {
            "invocation" : "403f534febb09e71cd06ee3b8109fce0e90aec2e1c65489ad8ecc579e001c07810cab0bbbaf843bead4c2eccc2e45ffeb8d5e4e7a77ed43b704db8ce64fae74b75409e0ceca68c9416313bc5083ee69438b83633a88fe2b7af2c738def8e2d93e9d30e72edca129f0ac0d892247cd7141eceaa3e3712c93345a943b524d1ccd0273840552600838f3a25bf25cbbf123fbe6cbca6080df91752c60e154364fb4bb9100343f5b450903c32586f66fbb4e9711205e1eef75208c3cef68feb0f08213ba07040f2af790100088c157358891126eee3a315434af66b183223b106ec411f7dd7496238b53616cbc18a819657ff0d42ff7285f06d9ed187a892893db6ab73a4b975403a030bce8b77d1f5b8147f70a0ff7a5740e4f1c1ce56dbdb4abc3b797ff3a1c9ed1eeea500b2e0c964a7ae4235e17245529cc8d857a938d9dd5eb6fb514aeb34",
            "verification" : "5521024c7b7fb6c310fccf1ba33b082519d82964ea93868d676662d4a59ad548df0e7d21025bdf3f181f53e9696227843950deb72dcd374ded17c057159513c3d0abe20b642103b209fd4f53a7170ea4444e0cb0a6bb6a53c2bd016926989cf85f9b0fba17a70c2103b8d9d5771d8f513aa0869b9cc8d50986403b78c6da36890638c3d46a5adce04a2103c346b984b5ad1a7b0ab019f1550fd783108f83a6ca5396b152c7aa302b87ed5b2102ca0e27697b9c248f6f16e085fd0061e26f44da85b58ee835c110caa5ec3ba5542102df48f60e8f3e01c48ff40b9b7f1310d7a8b2a193188befe1c2e3df740e89509357ae"
         }
      }
   },
   "jsonrpc" : "2.0"
}
```
Not sure what could be wrong the config… as it is consistent with the issue thread. Our current configuration looks like:

```
ProtocolConfiguration:
  Magic: 7630401
  AddressVersion: 23
  SecondsPerBlock: 15
  LowPriorityThreshold: 0.001
  MemPoolSize: 50000
  StandbyValidators:
  - 03b209fd4f53a7170ea4444e0cb0a6bb6a53c2bd016926989cf85f9b0fba17a70c
  - 02df48f60e8f3e01c48ff40b9b7f1310d7a8b2a193188befe1c2e3df740e895093
  - 03b8d9d5771d8f513aa0869b9cc8d50986403b78c6da36890638c3d46a5adce04a
  - 02ca0e27697b9c248f6f16e085fd0061e26f44da85b58ee835c110caa5ec3ba554
  - 024c7b7fb6c310fccf1ba33b082519d82964ea93868d676662d4a59ad548df0e7d
  - 02aaec38470f6aad0042c6e877cfd8087d2676b0f516fddd362801b9bd3936399e
  - 02486fd15702c4490a26703112a5cc1d0923fd697a33406bd5a1c00e0013b09a70
  SeedList:
  - seed1.ngd.network:10333
  - seed2.ngd.network:10333
  - seed3.ngd.network:10333
  - seed4.ngd.network:10333
  - seed5.ngd.network:10333
  - seed6.ngd.network:10333
  - seed7.ngd.network:10333
  - seed8.ngd.network:10333
  - seed9.ngd.network:10333
  - seed10.ngd.network:10333
  SystemFee:
    EnrollmentTransaction: 1000
    IssueTransaction: 500
    PublishTransaction: 500
    RegisterTransaction: 10000
  VerifyBlocks: true
  VerifyTransactions: false
  FreeGasLimit: {0: 10.0, 6200000: 50.0}
  MaxTransactionsPerBlock: {0: 500, 6200000: 200}
  MaxFreeTransactionsPerBlock: {0: 20, 6200000: 199}
  MaxFreeTransactionSize: 1024
  MinimumNetworkFee: 0
  FeePerExtraByte: 0.00001
ApplicationConfiguration:
  # LogPath could be set up in case you need stdout logs to some proper file.
  # LogPath: "./log/neogo.log"
  DBConfiguration:
    Type: "boltdb" #other options: 'inmemory','redis','boltdb', 'badgerdb'.
    # DB type options. Uncomment those you need in case you want to switch DB type.
    LevelDBOptions:
      DataDirectoryPath: "./chains/mainnet"
  #    RedisDBOptions:
  #      Addr: "localhost:6379"
  #      Password: ""
  #      DB: 0
    BoltDBOptions:
      FilePath: "./chains/mainnet.bolt"
  #    BadgerDBOptions:
  #      BadgerDir: "./chains/mainnet.badger"
  #  Uncomment in order to set up custom address for node.
  #  Address: 127.0.0.1
  NodePort: 10333
  Relay: true
  DialTimeout: 3
  ProtoTickInterval: 2
  PingInterval: 30
  PingTimeout: 90
  MaxPeers: 100
  AttemptConnPeers: 20
  MinPeers: 5
  RPC:
    Enabled: true
    EnableCORSWorkaround: false
    Port: 10332
    TLSConfig:
      Enabled: false
      Port: 10331
      CertFile: serv.crt
      KeyFile: serv.key
  Prometheus:
    Enabled: true
    Port: 2112
  Pprof:
    Enabled: false
    Port: 2113
```
