### ISSUE TITLE
neo-go dont work with config file

### ISSUE THREAD

**Issue by Alexpast1423** [nspcc-dev/neo-go#2623]
Hi !
I have a neo-go version :
```
apastukhov@ansiblerunner: downloads/neo-go-linux-amd64 --version
neo-go version 0.99.1-pre-197-g68b5260f
```
And i have a config
```
cat configuration/config.yaml
rpc-endpoint: http://xx.xxx.xxx.xxx:40332
alphabet-wallets: configuration/alphabet-wallets
network:
  max_object_size: 13421728
  epoch_duration: 450
  basic_income_rate: 0
  homomorphic_hash_disabled: true
  fee:
    audit: 0
    candidate: 0
    container: 0
    container_alias: 0
    withdraw: 0
credentials:
  contract: ''
  az: ''
  buky: ''
  vedi: ''
  glagoli: ''
```

When i'm creating wallets for S3 i'm using command:
```
downloads/neo-go-linux-amd64 wallet init -a -w configuration/wallets/node23-s3.json
```
And must answer to promt
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/60607653/182622696-642f12b6-e720-4973-9c52-aa8d5c99d529.png">

when i'm add -c flag i have error:
```
root@ansiblerunner:/jenkins/workspace/sbercloud_deploy/apastukhov/Morph# downloads/neo-go-linux-amd64 wallet init -a -w configuration/wallets/node23-s3.json -c configuration/config.yaml
Incorrect Usage: flag provided but not defined: -c

NAME:
   neo-go wallet init - create a new wallet

USAGE:
   neo-go wallet init [command options] [arguments...]

OPTIONS:
   --wallet value, -w value  Target location of the wallet file ('-' to read from stdin); conflicts with --wallet-config flag.
   --wallet-config value     Target location of the wallet config file; conflicts with --wallet flag.
   --account, -a             Create a new account

panic: flag provided but not defined: -c

goroutine 1 [running]:
main.main()
	./main.go:20 +0x4d
```

Ok, i'm add flag --wallet-config value
```
root@ansiblerunner:/jenkins/workspace/sbercloud_deploy/apastukhov/Morph# downloads/neo-go-linux-amd64 wallet init -a -w configuration/wallets/123-s3.json --wallet-config configuration/config.yaml
panic: --wallet flag conflicts with --wallet-config flag, please, provide one of them to specify wallet location

goroutine 1 [running]:
main.main()
	./main.go:20 +0x4d
```

Task https://github.com/nspcc-dev/neo-go/issues/2536 is closed, but not working ....
