### ISSUE TITLE
Push additional type data into bindings for RPC generator to use

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#2767]
We have the following data in the bindings config file:
```
    ownerOf: github.com/nspcc-dev/neo-go/pkg/interop.Hash160
    ownerOf.tokenID: '[]byte'
```
It can be reused by RPC bindings generator (some directly, some through a mapper), but we also have things like
```
    putNameStateWithKey.ns: github.com/nspcc-dev/neo-go/examples/nft-nd-nns.NameState
```
The idea is to add a section for structured types, like this:
```
types:
    github.com/nspcc-dev/neo-go/examples/nft-nd-nns.NameState:
        - field1: type
        - field2: type
        - ...
```
We can expand this type data and make it available to the RPC bindings generator, then it could create appropriate data types. Maybe some day it could be moved into manifest JSON.
