### ISSUE TITLE
neo-go.service doesn't start if one of the interfaces is down

### ISSUE THREAD

**Issue by ikovalev1** [nspcc-dev/neo-go#2878]
neo-go.service can be configured to listen several IP interfaces, e.g
```
ApplicationConfiguration:
  P2P:
    Addresses:
      - "192.168.201.121:40333"
      - "192.168.201.141:40333"
```

If on of the interfaces is down
```
ifdown data1
```
and neo-go service is restarted, the service doesn't start
```
systemctl restart neo-go

systemctl status neo-go
● neo-go.service - NeoGo N3-neo-go node
     Loaded: loaded (/lib/systemd/system/neo-go.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/neo-go.service.d
             └─limits.conf
     Active: activating (auto-restart) (Result: exit-code) since Tue 2023-01-17 09:32:21 UTC; 367ms ago
    Process: 2411 ExecStart=/usr/bin/neo-go node --mainnet --config-path=/etc/neofs/neo-go (code=exited, status=2)
   Main PID: 2411 (code=exited, status=2)
        CPU: 826ms

Jan 17 09:32:21 az systemd[1]: neo-go.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 17 09:32:21 az systemd[1]: neo-go.service: Failed with result 'exit-code'.
```
