### ISSUE TITLE
`(*neo.ContractReader).GetAllCandidates` doesn't work as expected

### ISSUE THREAD

**Issue by AnnaShaleva** [nspcc-dev/neo-go#3106]
Originally posted by @cthulhu-rider.

## Current Behavior

The following script gives the unexpected result on NeoFS devenv with single local consensus node and disabled server-side iterator sessions:
```
simple: 1
iter: 0
```
```
func TestCandidates(t *testing.T) {
	const sidechainEndpoint = "wss://rpc1.morph.t5.fs.neo.org:51331/ws"
	
	ws, err := rpcclient.NewWS(context.Background(), sidechainEndpoint, rpcclient.Options{})
	require.NoError(t, err)
	t.Cleanup(ws.Close)

	require.NoError(t, ws.Init())

	neoContract := neo.NewReader(invoker.New(ws, nil))

	candidates, err := neoContract.GetCandidates()
	require.NoError(t, err)
	fmt.Println("simple:", len(candidates))

	iter, err := neoContract.GetAllCandidates()
	require.NoError(t, err)

	var candidatesIter []result.Validator

	for {
		next, err := iter.Next(10)
		require.NoError(t, err)

		candidatesIter = append(candidatesIter, next...)

		if len(next) == 0 {
			require.NoError(t, iter.Terminate())
			break
		}
	}

	fmt.Println("iter:", len(candidatesIter))
}
```

## Expected Behavior
`simple` and `iter` results should match. I've checked sessions-disabled iterator traversal on the client side and it works properly, need some additional investigation.

**Comment by cthulhu-rider** [comment]
it should be noted that i didn't use config loader https://pkg.go.dev/github.com/nspcc-dev/neo-go@v0.101.4/pkg/config#LoadFile which sets some defaults

raw config was:
```yaml
ProtocolConfiguration:
    CommitteeHistory: {}
    GarbageCollectionPeriod: 0
    Magic: 15405
    MemPoolSize: 0
    Hardforks: {}
    InitialGASSupply: "0"
    P2PNotaryRequestPayloadPoolSize: 0
    KeepOnlyLatestState: false
    RemoveUntraceableBlocks: false
    MaxBlockSize: 0
    MaxBlockSystemFee: 0
    MaxTraceableBlocks: 200000
    MaxTransactionsPerBlock: 0
    MaxValidUntilBlockIncrement: 0
    NativeActivations: {}
    P2PSigExtensions: true
    P2PStateExchangeExtensions: false
    ReservedAttributes: false
    SaveStorageBatch: false
    SecondsPerBlock: 0
    SeedList:
        - :20333
    StandbyCommittee:
        - 02b3622bf4017bdfe317c58aed5f4c753f206b7db896046fa7d774bbc4bf7f8dc2
    StateRootInHeader: false
    StateSyncInterval: 0
    TimePerBlock: 1s
    ValidatorsCount: 1
    ValidatorsHistory: {}
    VerifyBlocks: false
    VerifyTransactions: true
ApplicationConfiguration:
    GarbageCollectionPeriod: 0
    KeepOnlyLatestState: false
    RemoveUntraceableBlocks: false
    SaveStorageBatch: false
    SkipBlockVerification: false
    AttemptConnPeers: 0
    BroadcastFactor: 0
    DBConfiguration:
        Type: ""
        LevelDBOptions:
            DataDirectoryPath: ""
            ReadOnly: false
        BoltDBOptions:
            FilePath: ""
            ReadOnly: false
    DialTimeout: 0
    LogLevel: ""
    LogPath: ""
    MaxPeers: 0
    MinPeers: 0
    P2P:
        Addresses:
            - :20333
        AttemptConnPeers: 5
        BroadcastFactor: 0
        DialTimeout: 3s
        ExtensiblePoolSize: 0
        MaxPeers: 10
        MinPeers: 0
        PingInterval: 30s
        PingTimeout: 1m30s
        ProtoTickInterval: 2s
    PingInterval: 0
    PingTimeout: 0
    Pprof:
        Enabled: false
        Addresses: []
    Prometheus:
        Enabled: false
        Addresses: []
    ProtoTickInterval: 0
    Relay: true
    Consensus:
        Enabled: true
        UnlockWallet:
            Path: /wallet.json
            Password: one
    RPC:
        Enabled: true
        Addresses:
            - :30333
        EnableCORSWorkaround: false
        MaxGasInvoke: "100"
        MaxIteratorResultItems: 0
        MaxFindResultItems: 0
        MaxNEP11Tokens: 0
        MaxWebSocketClients: 0
        SessionEnabled: false
        SessionExpirationTime: 0
        SessionBackedByMPT: false
        SessionPoolSize: 0
        StartWhenSynchronized: true
        TLSConfig:
            Enabled: false
            Addresses: []
            CertFile: ""
            KeyFile: ""
    UnlockWallet:
        Path: /wallet.json
        Password: one
    Oracle:
        Enabled: false
        AllowPrivateHost: false
        AllowedContentTypes: []
        Nodes: []
        NeoFS:
            Nodes: []
            Timeout: 0s
        MaxTaskTimeout: 0s
        RefreshInterval: 0s
        MaxConcurrentRequests: 0
        RequestTimeout: 0s
        ResponseTimeout: 0s
        UnlockWallet:
            Path: ""
            Password: ""
    P2PNotary:
        Enabled: true
        UnlockWallet:
            Path: /wallet.json
            Password: one
    StateRoot:
        Enabled: false
        UnlockWallet:
            Path: ""
            Password: ""
    ExtensiblePoolSize: 0
```
