### ISSUE TITLE
panic: interface conversion: dao.NativeContractCache is nil, not *native.PolicyCache

### ISSUE THREAD

**Issue by 532910** [nspcc-dev/neo-go#3181]
```
% ./neo-go-linux-amd64 node --config-file config.yml
2023-10-31T20:13:12.354+0300	INFO	P2PNotaryRequestPayloadPool size is not set or wrong, setting default value	{"P2PNotaryRequestPayloadPoolSize": 1000}
2023-10-31T20:13:12.354+0300	INFO	MaxBlockSize is not set or wrong, setting default value	{"MaxBlockSize": 262144}
2023-10-31T20:13:12.354+0300	INFO	MaxBlockSystemFee is not set or wrong, setting default value	{"MaxBlockSystemFee": 900000000000}
2023-10-31T20:13:12.354+0300	INFO	MaxTransactionsPerBlock is not set or wrong, using default value	{"MaxTransactionsPerBlock": 512}
2023-10-31T20:13:12.354+0300	INFO	MaxValidUntilBlockIncrement is not set or wrong, using default value	{"MaxValidUntilBlockIncrement": 5760}
2023-10-31T20:13:12.354+0300	INFO	Hardforks are not set, using default value
2023-10-31T20:13:12.356+0300	INFO	restoring blockchain	{"version": "0.2.10"}
panic: interface conversion: dao.NativeContractCache is nil, not *native.PolicyCache

goroutine 1 [running]:
github.com/nspcc-dev/neo-go/pkg/core/native.(*Policy).isBlockedInternal(0xc000f97340?, 0xc000fff080?, {0x4e, 0x7d, 0x51, 0x11, 0xe7, 0x22, 0x2f, 0xd8, ...})
	github.com/nspcc-dev/neo-go/pkg/core/native/policy.go:258 +0x149
github.com/nspcc-dev/neo-go/pkg/core/native.(*Policy).IsBlocked(...)
	github.com/nspcc-dev/neo-go/pkg/core/native/policy.go:250
github.com/nspcc-dev/neo-go/pkg/core/native.(*NEO).getCandidates.func1({0xc000f55596, 0x21, 0x21}, {0xc001002130, 0xa, 0xa})
	github.com/nspcc-dev/neo-go/pkg/core/native/native_neo.go:981 +0x1d1
github.com/nspcc-dev/neo-go/pkg/core/dao.(*Simple).Seek.func1({0xc000f55590?, 0x0?, 0x0?}, {0xc001002130?, 0x10d6ac0?, 0x0?})
	github.com/nspcc-dev/neo-go/pkg/core/dao/dao.go:387 +0x45
github.com/nspcc-dev/neo-go/pkg/core/storage.performSeek.func3({0x7fb075b6576d, 0x27, 0x410725?}, {0x7fb075b65794, 0xa, 0x1?})
	github.com/nspcc-dev/neo-go/pkg/core/storage/memcached_store.go:294 +0x46a
github.com/nspcc-dev/neo-go/pkg/core/storage.(*BoltDBStore).Seek.func1(0xc000ff7ae0?, {0x7fb075b6576d?, 0x2?, 0x0?}, {0x7fb075b65794?, 0x3fe0000000000000?, 0xc00037a168?})
	github.com/nspcc-dev/neo-go/pkg/core/storage/boltdb_store.go:131 +0x34
github.com/nspcc-dev/neo-go/pkg/core/storage.boltSeek.func1(0x60?)
	github.com/nspcc-dev/neo-go/pkg/core/storage/boltdb_store.go:163 +0x2f0
go.etcd.io/bbolt.(*DB).View(0x10edf20?, 0xc000ff0480)
	go.etcd.io/bbolt@v1.3.7/db.go:893 +0x72
github.com/nspcc-dev/neo-go/pkg/core/storage.boltSeek(0xc00037a2c8, {{0xc001002060, 0x6, 0x6}, {0x0, 0x0, 0x0}, 0x0, 0x0}, 0xc000125730)
	github.com/nspcc-dev/neo-go/pkg/core/storage/boltdb_store.go:140 +0x13a
github.com/nspcc-dev/neo-go/pkg/core/storage.(*BoltDBStore).Seek(0x1d95580?, {{0xc001002060, 0x6, 0x6}, {0x0, 0x0, 0x0}, 0x0, 0x0}, 0xc0002cebd0)
	github.com/nspcc-dev/neo-go/pkg/core/storage/boltdb_store.go:130 +0xf2
github.com/nspcc-dev/neo-go/pkg/core/storage.performSeek({0x148fd78, 0x1d929a0}, {0x1491018, 0xc00011a008}, {0x0, 0x0, 0x0}, {{0xc001002060, 0x6, 0x6}, ...}, ...)
	github.com/nspcc-dev/neo-go/pkg/core/storage/memcached_store.go:308 +0x475
github.com/nspcc-dev/neo-go/pkg/core/storage.(*MemCachedStore).Seek(0x0?, {{0xc001002060, 0x6, 0x6}, {0x0, 0x0, 0x0}, 0x0, 0x0}, 0xc000ffa640)
	github.com/nspcc-dev/neo-go/pkg/core/storage/memcached_store.go:157 +0xe8
github.com/nspcc-dev/neo-go/pkg/core/dao.(*Simple).Seek(0xc000172400, 0xfffffffb, {{0xc001002060, 0x6, 0x6}, {0x0, 0x0, 0x0}, 0x0, 0x0}, ...)
	github.com/nspcc-dev/neo-go/pkg/core/dao/dao.go:386 +0x2b2
github.com/nspcc-dev/neo-go/pkg/core/native.(*NEO).getCandidates(0xc0001ea2c0, 0xc000172400, 0x0, 0xffffffffffffffff)
	github.com/nspcc-dev/neo-go/pkg/core/native/native_neo.go:978 +0x1e9
github.com/nspcc-dev/neo-go/pkg/core/native.(*NEO).computeCommitteeMembers(0xc0001ea2c0, 0x563a7, 0xc000fe7eb0?)
	github.com/nspcc-dev/neo-go/pkg/core/native/native_neo.go:1192 +0x1cd
github.com/nspcc-dev/neo-go/pkg/core/native.(*NEO).updateCachedNewEpochValues(0xc0001ea2c0?, 0xc000f4fd40?, 0xc000f4fd40, 0x1?, 0x7)
	github.com/nspcc-dev/neo-go/pkg/core/native/native_neo.go:399 +0x2f
github.com/nspcc-dev/neo-go/pkg/core/native.(*NEO).InitializeCache(0xc0001ea2c0, 0x563a7, 0x1f5ea5be9dd67767?)
	github.com/nspcc-dev/neo-go/pkg/core/native/native_neo.go:351 +0x48a
github.com/nspcc-dev/neo-go/pkg/core.(*Blockchain).initializeNativeCache(0xc000172c80?, 0x563a7, 0x1?)
	github.com/nspcc-dev/neo-go/pkg/core/blockchain.go:1025 +0xac
github.com/nspcc-dev/neo-go/pkg/core.(*Blockchain).init(0xc000005500)
	github.com/nspcc-dev/neo-go/pkg/core/blockchain.go:475 +0x62e
github.com/nspcc-dev/neo-go/pkg/core.NewBlockchain({0x1491018?, 0xc00011a008}, {{0x0, {0x0, 0x0}, 0x2bdb2b5f, 0xc350, 0xc0003c6510, 0x12795f58d50000, 0x3e8, ...}, ...}, ...)
	github.com/nspcc-dev/neo-go/pkg/core/blockchain.go:331 +0x1898
github.com/nspcc-dev/neo-go/cli/server.initBlockChain({{0x0, {0x0, 0x0}, 0x2bdb2b5f, 0xc350, 0x0, 0x12795f58d50000, 0x0, 0x0, 0x0, ...}, ...}, ...)
	github.com/nspcc-dev/neo-go/cli/server/server.go:656 +0x207
github.com/nspcc-dev/neo-go/cli/server.initBCWithMetrics({{0x0, {0x0, 0x0}, 0x2bdb2b5f, 0xc350, 0x0, 0x12795f58d50000, 0x0, 0x0, 0x0, ...}, ...}, ...)
	github.com/nspcc-dev/neo-go/cli/server/server.go:135 +0x58
github.com/nspcc-dev/neo-go/cli/server.startServer(0xc00017a840)
	github.com/nspcc-dev/neo-go/cli/server/server.go:464 +0x545
github.com/urfave/cli.HandleAction({0xff7440?, 0x13339f0?}, 0x4?)
	github.com/urfave/cli@v1.22.5/app.go:524 +0x50
github.com/urfave/cli.Command.Run({{0x11dc19a, 0x4}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x11ebab4, 0x12}, {0x1223796, ...}, ...}, ...)
	github.com/urfave/cli@v1.22.5/command.go:173 +0x63e
github.com/urfave/cli.(*App).Run(0xc0001716c0, {0xc00003e080, 0x4, 0x4})
	github.com/urfave/cli@v1.22.5/app.go:277 +0xb07
main.main()
	./main.go:12 +0x2d
zsh: exit 2     ./neo-go-linux-amd64 node --config-file config.yml
```

steps to reproduce:
1. start neogo with no database
2. interrupt with ctrl-c, it will say:
```
^C2023-10-31T20:11:54.815+0300	INFO	shutting down server	{"peers": 11}
2023-10-31T20:11:54.815+0300	WARN	peer disconnected	{"addr": "170.64.152.72:51333", "error": "server shutdown", "peerCount": 10}
2023-10-31T20:11:54.815+0300	WARN	peer disconnected	{"addr": "65.108.90.74:51333", "error": "server shutdown", "peerCount": 9}
2023-10-31T20:11:54.815+0300	WARN	peer disconnected	{"addr": "159.203.28.78:51333", "error": "server shutdown", "peerCount": 8}
2023-10-31T20:11:54.815+0300	WARN	peer disconnected	{"addr": "49.12.226.190:50333", "error": "server shutdown", "peerCount": 7}
2023-10-31T20:11:54.815+0300	WARN	peer disconnected	{"addr": "5.78.81.79:51333", "error": "server shutdown", "peerCount": 6}
2023-10-31T20:11:54.815+0300	WARN	peer disconnected	{"addr": "49.12.226.190:51333", "error": "server shutdown", "peerCount": 5}
2023-10-31T20:11:54.815+0300	WARN	peer disconnected	{"addr": "170.64.152.72:50333", "error": "server shutdown", "peerCount": 4}
2023-10-31T20:11:54.815+0300	WARN	peer disconnected	{"addr": "116.203.249.217:50333", "error": "server shutdown", "peerCount": 3}
2023-10-31T20:11:54.815+0300	WARN	peer disconnected	{"addr": "167.71.212.120:50333", "error": "server shutdown", "peerCount": 2}
2023-10-31T20:11:54.815+0300	WARN	peer disconnected	{"addr": "159.203.28.78:50333", "error": "server shutdown", "peerCount": 1}
2023-10-31T20:11:54.815+0300	WARN	peer disconnected	{"addr": "65.108.90.74:50333", "error": "server shutdown", "peerCount": 0}
2023-10-31T20:11:55.201+0300	INFO	persisted to disk	{"blocks": 1367, "keys": 22958, "headerHeight": 353191, "blockHeight": 353191, "took": "385.464896ms"}
```
3. start it again
4. repeat untill subj

**Comment by AnnaShaleva** [comment]
Config, please! And attach the binary version.

**Comment by 532910** [comment]
get it from one of our nodes
neogo version is the latest release -- 103

**Comment by AnnaShaleva** [comment]
Attach the node configuration, please.

**Comment by 532910** [comment]
```Yaml
ApplicationConfiguration:
  DBConfiguration:
    BoltDBOptions:
      FilePath: /var/lib/neogo/morph-rpc/mainnet.bolt
    Type: boltdb
  P2P:
    Addresses:
    - 116.203.249.217:51333
    AttemptConnPeers: 20
    DialTimeout: 3s
    MaxPeers: 100
    MinPeers: 4
    PingInterval: 30s
    PingTimeout: 90s
    ProtoTickInterval: 2s
  Pprof:
    Addresses:
    - localhost:2133
    Enabled: true
  Prometheus:
    Addresses:
    - localhost:2132
    Enabled: true
  RPC:
    Addresses:
    - 116.203.249.217:51332
    EnableCORSWorkaround: false
    Enabled: true
    MaxGasInvoke: 100
    StartWhenSynchronized: false
    TLSConfig:
      Addresses:
      - 116.203.249.217:51331
      CertFile: /etc/neogo/morph-rpc/server.crt
      Enabled: true
      KeyFile: /etc/neogo/morph-rpc/server.key
  Relay: true
ProtocolConfiguration:
  InitialGASSupply: 52000000
  Magic: 735783775
  MaxTraceableBlocks: 2102400
  MemPoolSize: 50000
  NativeActivations:
    ContractManagement:
    - 0
    CryptoLib:
    - 0
    GasToken:
    - 0
    LedgerContract:
    - 0
    NeoToken:
    - 0
    Notary:
    - 0
    OracleContract:
    - 0
    PolicyContract:
    - 0
    RoleManagement:
    - 0
    StdLib:
    - 0
  P2PSigExtensions: true
  SeedList:
  - morph1.t5.fs.neo.org:50333
  - morph2.t5.fs.neo.org:50333
  - morph3.t5.fs.neo.org:50333
  - morph4.t5.fs.neo.org:50333
  - morph5.t5.fs.neo.org:50333
  - morph6.t5.fs.neo.org:50333
  - morph7.t5.fs.neo.org:50333
  StandbyCommittee:
  - 0337f5f45e5be5aeae4a919d0787fcb743656560949061d5b8b05509b85ffbfd53
  - 020b86534a9a264d28b79155b0ec36d555ed0068eb1b0c4d40c35cc7d2f04759b8
  - 02c2efdc01181b0bc14fc19e0acb12281396c8c9ffe64458d621d781a1ded436b7
  - 026f9b40a73f29787ef5b289ac845bc43c64680fdd42fc170b1171d3c57213a89f
  - 0272350def90715494b857315c9b9c70181739eeec52d777424fef2891c3396cad
  - 03a8cee2d3877bcce5b4595578714d77ca2d47673150b8b9cd4e391b7c73b6bda3
  - 0215e735a657f6e23478728d1d0718d516bf50c06c2abd92ec7c00eba2bd7a2552
  StateRootInHeader: false
  TimePerBlock: 15s
  ValidatorsCount: 7
  VerifyBlocks: true
  VerifyTransactions: true
```
