### ISSUE TITLE
Check NeoFS chains compatibility with limited MaxTraceableBlocks

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neo-go#3493]
## Is your task related to a problem? Please describe.
I'm always frustrated when we have a loooong tail of history in NeoFS chains. Refs. https://github.com/neo-project/neo/issues/2026.

## Describe the solution you'd like
Try synchronizing with `MaxTraceableBlocks` of 5760 (a day), if it works --- OK immediately. If it doesn't --- try with 40320 (a week). Success criteria: same state computed for the current height. I expect 40320 to be a bit more realistic setting for a real network, but we need to know our possibilities.

**Comment by AnnaShaleva** [comment]
> state differs at 5800000, block fe5278cd6dce728384a2c2ed40c511e5813c56a67c499eecef758709a8234065

OK, it's just came to my mind that it's a hardfork height. @AliceInHunterland, what is your node configuration?

**Comment by AliceInHunterland** [comment]
MaxTraceableBlocks: 40320
```
(base) ekaterinapavlova@MacBook-Air-4 neo-go % go run scripts/compare-states/compare-states.go --ignore-height http://localhost:40332 https://rpc1.morph.fs.neo.org:40341
at 0: 437e6b95ac529ede8685071a29471f096ea8d6824b916c0e7ca6d8017b2a23ed vs 437e6b95ac529ede8685071a29471f096ea8d6824b916c0e7ca6d8017b2a23ed
at 5986178: f17ce90bf1068b466a8531cc44982faeff4bb982154e85f18d60ef8beafb0020 vs 7538bef334d486c1854bfb010d85eab1a52fa2791f60137d709312098d47d38a
at 2993089: 34d34f7ca47514f296464d7344e8b66af24326cac98300c64ab363f7def712e3 vs 34d34f7ca47514f296464d7344e8b66af24326cac98300c64ab363f7def712e3
at 4489633: 6869a6373c127352a8476d0e80e0c8da6307579fae8540f8b3c781e1316262a0 vs 6869a6373c127352a8476d0e80e0c8da6307579fae8540f8b3c781e1316262a0
at 5237905: 5a493dd3c7c031ab8893aa96d5145086474f544ae9609768f3930bbbb544eb50 vs 5a493dd3c7c031ab8893aa96d5145086474f544ae9609768f3930bbbb544eb50
at 5612041: 4d44d1f9581c060102c4923873e7e4cfe0d18fb72027b73843c27cfae6e954a3 vs 4d44d1f9581c060102c4923873e7e4cfe0d18fb72027b73843c27cfae6e954a3
at 5799109: ed9a6bed42da09826418e95a5da9348caa3d567102e636027a654efc9c64bbdd vs ed9a6bed42da09826418e95a5da9348caa3d567102e636027a654efc9c64bbdd
at 5892643: bdba1ad296c01db38e68005c68e11abb0ca982aab186ffac984970e9f46daa4b vs 2c141d58c4aa88feea80bfb5964d1708fc0c993a5a61589faa03fcefae004450
at 5845876: 5ca6145cf757bba9acc5ccbad03464b03feda1fb723d1b6114278a0b24f05490 vs 3083f99449e4009746c6d34bb40ff605ce955ba75b457c7804c25d45a0b1d287
at 5822492: a6dc5d1fe2b54eec8ddac1002f88062e8044b3652f9893caa403c505f7876c9e vs 507ddbc609532c6dc10ec5105c1f05fccdb03b2545783bd5f02a00f70dae0430
at 5810800: 9ba614518407bf6defb79a3d2de48509d25c35488b01663fd6ff634b6d30b754 vs 568d3914ca4251af35f296980c105452023002fe9b19c68204d9d4eff2bd6ce5
at 5804954: 7cd8ff27fcacc412395c1ec12f2e1ffeb4b3f9f87676c7f8763b792556432f07 vs d3d8c56b29ad4dfababa780c98f4a3eb850e391661d8a3650ec36084d97b886c
at 5802031: 5be537b1abbef21b7724f507d2dbf5438dc1493c3b2fd41b48cfedd319fad9a0 vs 74bf23e104b17601d380131e1bdfb3c6b168fed3a3dea2f7e62ce7fa8cb62d70
at 5800570: b8c2ba655419149329b0fb9d58aef785476834e5d4a5862282a76f3a934bdfb9 vs 1c6ab63f00de08f0ba1d4fad0b68e6231a672dda1bed192d348f709a49de29a6
at 5799839: 05c46c0a90b7fb53d646c5ada326c616abc074b74094a3adc25dbbeb687cd03e vs 05c46c0a90b7fb53d646c5ada326c616abc074b74094a3adc25dbbeb687cd03e
at 5800204: 4306c403a19c9e3d654f33d73c818460f0c12fef5265e44dac78da55751e7f69 vs 272ddbd84f59ca2129e4fa611e0bc0e0a94143cfbd4d4cb0a4b1a7042b8044e8
at 5800021: b51b9ce423e37e77d365a4103fbf464eb26889a5fabd79a91ddf13a88bebe821 vs 405ac96ae58149b196e8327ad6c1065b45277dfd0a148bb91bcd8117ab0922c6
at 5799930: 5fb5848951efdb0d45ff7f16e9bc5480c1b9e79b12081b1cd4a31f2c6f8691c3 vs 5fb5848951efdb0d45ff7f16e9bc5480c1b9e79b12081b1cd4a31f2c6f8691c3
at 5799975: 295b0e46f7459ad784792675011f73b90cc9aa819fd718bd53fbf428388ff0e6 vs 295b0e46f7459ad784792675011f73b90cc9aa819fd718bd53fbf428388ff0e6
at 5799998: f1487de7beab841d85da49a40ccd98c455815bb4472f7da66e3111a416b63125 vs f1487de7beab841d85da49a40ccd98c455815bb4472f7da66e3111a416b63125
at 5800009: 34eabecd11de72d7ca058d06f175d77c7782a63be6e794b2cd68853cf8381058 vs 06efa6753e9ebc75d1ce9eb008f2374bb46c6b9ae52e37cc6c3c457ca9268068
at 5800003: fd02eb0979b4b0053c40d7895e9b23d6958cdf21f10a6bf3f5a331b04e2de73e vs d96a9b8375444c7a6e255f34ff0bfea34bd5201cb9ae5e4a3aedfc095327dd89
at 5800000: 7b98a69a8941f32c2214da2759de0691067e9b68ca83b696ef98293912757367 vs 811c1e6936507dedc8964aa81888b7cb08acb681c08b29fb10568a38c0034b16
at 5799999: ceab104a9cac83db1e56cccc5bcdc0a735d605782664149661135479edb8853c vs ceab104a9cac83db1e56cccc5bcdc0a735d605782664149661135479edb8853c
state differs at 5800000, block fe5278cd6dce728384a2c2ed40c511e5813c56a67c499eecef758709a8234065
block fe5278cd6dce728384a2c2ed40c511e5813c56a67c499eecef758709a8234065:
--- http://localhost:40332
+++ https://rpc1.morph.fs.neo.org:40341
@@ -1,2 +1,2 @@
-(*result.ApplicationLog)(0x1400033ce40)({
+(*result.ApplicationLog)(0x1400041c240)({
  Container: (util.Uint256) (len=32 cap=32) 654023a8098775efec9e497ca6563c81e511c540edc2a2848372ce6dcd7852fe,
@@ -10,13 +10,3 @@
    },
-   Events: ([]state.NotificationEvent) (len=2 cap=2) {
-    (state.NotificationEvent) {
-     ScriptHash: (util.Uint160) (len=20 cap=20) fda3fa4346ea532a258fc497ddaddb6437c9fdff,
-     Name: (string) (len=6) "Update",
-     Item: (*stackitem.Array)(0x140004282a0)(Array)
-    },
-    (state.NotificationEvent) {
-     ScriptHash: (util.Uint160) (len=20 cap=20) fda3fa4346ea532a258fc497ddaddb6437c9fdff,
-     Name: (string) (len=6) "Update",
-     Item: (*stackitem.Array)(0x140004283c0)(Array)
-    }
+   Events: ([]state.NotificationEvent) {
    },
@@ -34,3 +24,3 @@
      Name: (string) (len=8) "Transfer",
-     Item: (*stackitem.Array)(0x14000428660)(Array)
+     Item: (*stackitem.Array)(0x14000352330)(Array)
     }

different state found
exit status 1
```

```
(base) ekaterinapavlova@MacBook-Air-4 neo-go % curl -X POST http://localhost:40332 -H 'Content-Type: application/json' -d '{
  "jsonrpc": "2.0",
  "method": "getblock",         
  "params": ["0xfe5278cd6dce728384a2c2ed40c511e5813c56a67c499eecef758709a8234065", 1],
  "id": 1   
}'| json_pp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1521  100  1377  100   144   154k  16496 --:--:-- --:--:-- --:--:--  212k
{
   "id" : 1,
   "jsonrpc" : "2.0",
   "result" : {
      "confirmations" : 186273,
      "hash" : "0xfe5278cd6dce728384a2c2ed40c511e5813c56a67c499eecef758709a8234065",
      "index" : 5800000,
      "merkleroot" : "0x0000000000000000000000000000000000000000000000000000000000000000",
      "nextblockhash" : "0xe72d9b47c79d9fd3c0c1f7fa9582865a9b423a14965c98470901837cfa6599b6",
      "nextconsensus" : "NN5r7AC1TQEuoKXyurXedNa1o5PawUtqkr",
      "nonce" : "98F3A4B00CBD0C4D",
      "previousblockhash" : "0xd6a2ab5966f464cecbf186169411509ca99fa95c9afb2234d279d70886e627fb",
      "primary" : 3,
      "size" : 697,
      "time" : 1717519541428,
      "tx" : [],
      "version" : 0,
      "witnesses" : [
         {
            "invocation" : "DEDwPCUy92VbKHURiTcyNG8mPheLLQUNQVM/kp73QfX31L7gbfrqgJNjr5BVZOKVekKjK3BFmbcSf6rjHq3ddY0NDECjzZzggwr30pdKkGfFzO80RYOw5D9smgSWgOHKQaVtFhRMAsqDzQGPfPEJ18oyWH6xAwayivSjCwdZrz0vc47rDEA3RpxIVVsBmiz2B7UkU0t0JtBkr+ONTp9jlgSrWHk3SYF4uvsLAoSBrSKovDYdg345hxOdlLhoeA0WwKT+No8UDEBL8EpCsIGpIbUi0Bx6A0cpdScgv9OVnDxifihCgdj+HFXPqyqNXmR49ODzpsWOC3iTryVDZNt3lPIYnuiKaE9eDECwJd8KvtsTGq9Qa89FhqW4RPWL0j9tnAsC6c0OIygTbxiU3WxO8QPlzifePkCDUzalAHo2KI2cOi4TqfjFoQUc",
            "verification" : "FQwhAx9NnGby7DSIMsSP06Ft+utZ6F9VeuHgf2aW0DdcZPl7DCECP5y3u+FU1SnVxxn9w5/qqDGkOuA9KkKAV1tg9S+nvFIMIQNaKhjN2volrTU96l5nMKG5/LS5GMSgMDxDh7ucO4Fq3wwhA2bSVefOI+pvfx5L7fXLr+WYcFtH5uwhPvE7LwgZ6KszDCECb6NOwFfXTC/fGhjjNtC9WX6kAaCyrVc0DVwiDQn0QIYMIQOanbKjCUKxhD22c66w1P1kM/dM7B2HneY0PLn892KPpAwhA5upWeCrbcYW34uANpLxwwupBxt2sFU165lL9bvEAq1fF0Ge0Nw6"
         }
      ]
   }
}
```


```
curl -X POST http://localhost:40332 -H 'Content-Type: application/json' -d '{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "getapplicationlog",
  "params": ["0xfe5278cd6dce728384a2c2ed40c511e5813c56a67c499eecef758709a8234065"]
}' | json_pp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1074  100   924  100   150    98k  16373 --:--:-- --:--:-- --:--:--  131k
{
   "id" : 1,
   "jsonrpc" : "2.0",
   "result" : {
      "blockhash" : "0xfe5278cd6dce728384a2c2ed40c511e5813c56a67c499eecef758709a8234065",
      "executions" : [
         {
            "exception" : null,
            "gasconsumed" : "0",
            "notifications" : [
               {
                  "contract" : "0xfffdc93764dbaddd97c48f252a53ea4643faa3fd",
                  "eventname" : "Update",
                  "state" : {
                     "type" : "Array",
                     "value" : [
                        {
                           "type" : "ByteString",
                           "value" : "G/V1qxGJaIQTYQo1oSiGzeC2bHI="
                        }
                     ]
                  }
               },
               {
                  "contract" : "0xfffdc93764dbaddd97c48f252a53ea4643faa3fd",
                  "eventname" : "Update",
                  "state" : {
                     "type" : "Array",
                     "value" : [
                        {
                           "type" : "ByteString",
                           "value" : "9WPqQLwoPU0OBcSOowWz8qBzQO8="
                        }
                     ]
                  }
               }
            ],
            "stack" : [],
            "trigger" : "OnPersist",
            "vmstate" : "HALT"
         },
         {
            "exception" : null,
            "gasconsumed" : "0",
            "notifications" : [
               {
                  "contract" : "0xd2a4cff31913016155e38e474a2c06d08be276cf",
                  "eventname" : "Transfer",
                  "state" : {
                     "type" : "Array",
                     "value" : [
                        {
                           "type" : "Any"
                        },
                        {
                           "type" : "ByteString",
                           "value" : "ADlC9CBAxnReI+C0UIICfvo1d6I="
                        },
                        {
                           "type" : "Integer",
                           "value" : "50000000"
                        }
                     ]
                  }
               }
            ],
            "stack" : [],
            "trigger" : "PostPersist",
            "vmstate" : "HALT"
         }
      ]
   }
}

```

**Comment by AliceInHunterland** [comment]
my config is:

```
ProtocolConfiguration:
  Magic: 91414437
  MaxTraceableBlocks: 40320
  InitialGASSupply: 52000000
  TimePerBlock: 15s
  MemPoolSize: 50000
  StandbyCommittee:
  - 026fa34ec057d74c2fdf1a18e336d0bd597ea401a0b2ad57340d5c220d09f44086
  - 039a9db2a30942b1843db673aeb0d4fd6433f74cec1d879de6343cb9fcf7628fa4
  - 0366d255e7ce23ea6f7f1e4bedf5cbafe598705b47e6ec213ef13b2f0819e8ab33
  - 023f9cb7bbe154d529d5c719fdc39feaa831a43ae03d2a4280575b60f52fa7bc52
  - 039ba959e0ab6dc616df8b803692f1c30ba9071b76b05535eb994bf5bbc402ad5f
  - 035a2a18cddafa25ad353dea5e6730a1b9fcb4b918c4a0303c4387bb9c3b816adf
  - 031f4d9c66f2ec348832c48fd3a16dfaeb59e85f557ae1e07f6696d0375c64f97b
  ValidatorsCount: 7
  SeedList:
  - morph1.fs.neo.org:40333
  - morph2.fs.neo.org:40333
  - morph3.fs.neo.org:40333
  - morph4.fs.neo.org:40333
  - morph5.fs.neo.org:40333
  - morph6.fs.neo.org:40333
  - morph7.fs.neo.org:40333
  VerifyTransactions: true
  P2PSigExtensions: true
  Hardforks:
    Aspidochelone: 3000000
    Basilisk: 4500000
    Cockatrice: 5800000
    Domovoi: 5800000

ApplicationConfiguration:
  SkipBlockVerification: false
  # LogPath could be set up in case you need stdout logs to some proper file.
  # LogPath: "./log/neogo.log"
  DBConfiguration:
    Type: "leveldb" #other options: 'inmemory','boltdb'
    # DB type options. Uncomment those you need in case you want to switch DB type.
    LevelDBOptions:
      DataDirectoryPath: "./chains/mainnet.neofs"
  #    BoltDBOptions:
  #      FilePath: "./chains/mainnet.bolt"
  P2P:
    Addresses:
      - ":40333" # in form of "[host]:[port][:announcedPort]"
    DialTimeout: 3s
    ProtoTickInterval: 2s
    PingInterval: 30s
    PingTimeout: 90s
    MaxPeers: 100
    AttemptConnPeers: 20
    MinPeers: 5
  Relay: true
  Consensus:
    Enabled: false
    UnlockWallet:
      Path: "/cn_wallet.json"
      Password: "pass"
  Oracle:
    Enabled: false
    AllowedContentTypes:
      - application/json
  RPC:
    Enabled: true
    Addresses:
      - ":40332"
    MaxGasInvoke: 15
    EnableCORSWorkaround: false
    TLSConfig:
      Enabled: false
      Addresses:
        - ":40331"
      CertFile: serv.crt
      KeyFile: serv.key
  Prometheus:
    Enabled: false
    Addresses:
      - ":2112"
  Pprof:
    Enabled: false
    Addresses:
      - ":2113"

```

and:
```
 ./bin/neo-go -v
NeoGo
Version: 0.106.3-pre-16-gda40f2de
GoVersion: go1.21.3

```
