### ISSUE TITLE
NeoFSBlockFetcher may seem hanging

### ISSUE THREAD

**Issue by 532910** [nspcc-dev/neo-go#3721]
with NeoFSBlockFetcher address set to ssl neogo silentlty doesn't work

steps to reproduce:
```Yaml
NeoFSBlockFetcher:
  Addresses:
    - st1.storage.fs.neo.org:443
    - st2.storage.fs.neo.org:443
    - st3.storage.fs.neo.org:443
    - st4.storage.fs.neo.org:443
```

log:
```
INFO        starting NeoFS BlockFetcher service
```
