### ISSUE TITLE
Seed node address can be blacklisted

### ISSUE THREAD

**Issue by AnnaShaleva** [nspcc-dev/neo-go#3902]
## Current Behavior
Node height stales due to inability to fetch new blocks. `getpeers` shows that all known peers are blacklisted:
```
anna@kiwi:~/Documents/GitProjects/nspcc-dev/neo-go$ curl -d '{ "jsonrpc": "2.0", "id": 1, "method": "getpeers", "params": ["0x398dbf659b3ea356845aafdc54227833550855e8956f5a9eae338c025dfa8a77"] }' http://192.168.43.94:7112 | json_pp 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   447  100   314  100   133   4535   1920 --:--:-- --:--:-- --:--:--  6478
{
   "id" : 1,
   "jsonrpc" : "2.0",
   "result" : {
      "bad" : [
         {
            "address" : "127.0.0.1",
            "port" : 20333
         },
         {
            "address" : "192.168.43.94",
            "port" : 20333
         },
         {
            "address" : "192.168.43.92",
            "port" : 20333
         },
         {
            "address" : "192.168.43.95",
            "port" : 20333
         },
         {
            "address" : "192.168.43.93",
            "port" : 20333
         },
         {
            "address" : "127.0.0.1",
            "port" : 57392
         }
      ],
      "connected" : [],
      "unconnected" : []
   }
}
```

It's known that some of thees peers are seed nodes.

## Expected Behavior
At least seed nodes must not be blacklisted.

## Possible Solution
Find the bug in this code, fix it:
https://github.com/nspcc-dev/neo-go/blob/66449003b3cd3e69c18fc4b03d8185407f25744d/pkg/network/discovery.go#L174-L181

**Comment by AnnaShaleva** [comment]
IR node config:
```
root@m181lt-ir-2:~# cat /mnt/metadata/local_state/config/config-ir.yaml

# Logger section
logger:
  level: warn # Logger level: one of "debug", "info" (default), "warn", "error", "dpanic", "panic", "fatal"

# Wallet settings
wallet:
  path: /morph/local_state/config/wallet-ir.json  # Path to NEP-6 NEO wallet file
  address: NYsRrQeVmqREiT59i9QmRX3M1nwU3vC46Y  # Account address in the wallet; ignore to use default address
  password: one  # Account password in the wallet

# Profiler section
pprof:
  enabled: false
  address: :6060  # Endpoint for application pprof profiling; disabled by default
  shutdown_timeout: 30s  # Timeout for profiling HTTP server graceful shutdown

# Application metrics section
prometheus:
  enabled: true
  address: localhost:9090  # Endpoint for application prometheus metrics; disabled by default
  shutdown_timeout: 30s  # Timeout for metrics HTTP server graceful shutdown

# Toggling the sidechain-only mode
without_mainnet: true

# Neo main chain RPC settings
mainnet:
  endpoints: # List of websocket RPC endpoints in mainchain; ignore if mainchain is disabled
    - ws://main-chain:30333/ws

# Neo side chain RPC settings
fschain:
  dial_timeout: 5s # Timeout for RPC client connection to sidechain
  reconnections_number: 5  # number of reconnection attempts
  reconnections_delay: 5s  # time delay b/w reconnection attempts
  validators: # List of hex-encoded 33-byte public keys of sidechain validators to vote for at application startup
    - 0244e23d9ac8f91fedcaf487c8249bff2eda17c898298d22794c0b8929a047a24d
    - 02d014f67915bacc5bf9890d786f29a27c721cd3d6de008d19e7ddc1bf08bcf86a
    - 03b2194f7e0cf23c65509ae2ee5caf3b1d27c449cd36ea545d93a0aa3e871ff4ef
    - 03dcc97069aa4bdecb05a47c68fe35a221ab2673b0be38469a3ad5ac9328339329
  consensus:
    magic: 15405
    committee:
      - 0244e23d9ac8f91fedcaf487c8249bff2eda17c898298d22794c0b8929a047a24d
      - 02d014f67915bacc5bf9890d786f29a27c721cd3d6de008d19e7ddc1bf08bcf86a
      - 03b2194f7e0cf23c65509ae2ee5caf3b1d27c449cd36ea545d93a0aa3e871ff4ef
      - 03dcc97069aa4bdecb05a47c68fe35a221ab2673b0be38469a3ad5ac9328339329
    storage:
      type: boltdb
      path: /morph/local_state/fschain.bolt
    time_per_block: 1s
    max_traceable_blocks: 200000
    seed_nodes:
      - :20333
      - 192.168.43.95:7111
      - 192.168.43.93:7111
      - 192.168.43.92:7111
    rpc:
      max_gas_invoke: 200
      max_websocket_clients: 512
      session_pool_size: 512
      listen:
        - ":30333"
    p2p_notary_request_payload_pool_size: 5000
    p2p:
      dial_timeout: 3s
      proto_tick_interval: 2s
      listen:
        - ":20333"
      peers:
        min: 2
        max: 9
        attempts: 20
      ping:
        interval: 3s
        timeout: 9s
    set_roles_in_genesis: true # Optional flag for designating P2PNotary and NeoFSAlphabet roles to all
      # genesis block validators. The validators depend on 'committee' and, if set, 'validators_history'.
      # Must be 'true' or 'false'.

fschain_autodeploy: true # Optional flag to run auto-deployment procedure of the FS chain. By default,
  # the chain is expected to be deployed/updated in the background (e.g. via NeoFS ADM tool).
  # If set, must be 'true' or 'false'.

# Internal worker pool configurations
workers:
  netmap: 100 # Default is 10 which is not enough for large clusters.

nns:
  system_email: ops@nspcc.io

# Network time settings
timers:
  stop_estimation:
    mul: 1  # Multiplier in x/y relation of when to stop basic income estimation within the epoch
    div: 4  # Divider in x/y relation of when to stop basic income estimation within the epoch
  collect_basic_income:
    mul: 1  # Multiplier in x/y relation of when to start basic income asset collection within the epoch
    div: 2  # Divider in x/y relation of when to start basic income asset collecting within the epoch
  distribute_basic_income:
    mul: 3  # Multiplier in x/y relation of when to start basic income asset distribution within the epoch
    div: 4  # Divider in x/y relation of when to start basic income asset distribution within the epoch

# Storage node GAS emission settings
emit:
  storage:
    amount: 1000000000  # Fixed8 value of sidechain GAS emitted to all storage nodes once per GAS emission cycle; disabled by default

# Audit settings
audit:
  pdp:
    max_sleep_interval: 100ms  # Maximum timeout between object.RangeHash requests to the storage node

# Settlement settings
settlement:
  basic_income_rate: 100000000  # Optional: override basic income rate value from network config; applied only in debug mode
  audit_fee: 100000  # Optional: override audit fee value from network config; applied only in debug mode

control:
  grpc:
    endpoint: ":16512"

experimental:
  chain_meta_data: true

node:
  persistent_state:
    path: /morph/local_state/neofs-ir-state # Path to application state file
```
