### ISSUE TITLE
Proposal: set non-zero defaults for ping

### ISSUE THREAD

**Issue by aprasolova** [nspcc-dev/neo-go#680]
I've been running neo-go node in single mode with the config below:
```
ProtocolConfiguration:
  Magic: 56753
  AddressVersion: 23
  SecondsPerBlock: 15
  LowPriorityThreshold: 0.001
  StandbyValidators:
  - 02b3622bf4017bdfe317c58aed5f4c753f206b7db896046fa7d774bbc4bf7f8dc2
  SeedList:
  - 127.0.0.1:20333
  SystemFee:
    EnrollmentTransaction: 1000
    IssueTransaction: 500
    PublishTransaction: 500
    RegisterTransaction: 10000
  VerifyBlocks: true
  VerifyTransactions: true

ApplicationConfiguration:
  DBConfiguration:
    Type: "boltdb"
    BoltDBOptions:
      FilePath: "/var/lib/neo-go/privnet.bolt"
  NodePort: 20333
  Relay: true
  DialTimeout: 3
  ProtoTickInterval: 2
  MaxPeers: 5
  MinPeers: 0
  AttemptConnPeers: 3
  RPC:
    Enabled: true
    EnableCORSWorkaround: true
    Port: 30333
  Prometheus:
    Enabled: True
    Port: 2112
  UnlockWallet:
    Path: "/etc/neo-go/wallet.json"
    Password: "one"
```
No ping timeouts were specified. I couldn't connect to neo-go node with a client. On neo-go node, I've been getting an error:
```WARN        peer disconnected        {"addr": "127.0.0.1:34562", "reason": "ping/pong timeout", "peerCount": 0}```

It took to add an explicit timeouts to configs, and I successfully connected.
```
PingInterval: 30
PingTimeout: 90
```

Looks like there are no defaults or it is set to zeros for above params.
What do you think on setting some non-zero defaults for these and maybe some other node parameters?
